### PR TITLE
Realtime collaboration using Yjs 

### PR DESCRIPTION
**Pull request by mohammed-bahumaish**
WIP

### CODE REVIEW

**Comment by l0g1x** [comment]
Is there any update on when this might get merged?

**Comment by mohammed-bahumaish** [comment]
> Is there any update on when this might get merged?

@l0g1x  it's not completed yet, i don't have an estimate time on when this is going to be merged as i work on it in my free time and I've been busy lately.

**Comment by mohammed-bahumaish** [comment]
@l0g1x just letting you know that it's merged :)

**Comment by l0g1x** [comment]
Nice! Will check it out

**Pull request merged**
